spring:
  data:
    redis:
      database: 6  #Redis??0~15????0
      host: localhost
      port: 6379
#      password:  #????????
      lettuce: # ??????lettuce??
        shutdown-timeout: 1000
        pool:
          max-active: 8   #????????????????????
          max-wait: -1  #???????????????????????
          max-idle: 5     #???????????
          min-idle: 0     #???????????
      timeout: 10000    #??????????

